HEADERS := algorithm.hpp bitset.hpp circular_buffer.hpp constructor.hpp deque.hpp event_emitter.hpp function.hpp future.hpp graph.hpp iterator.hpp map.hpp math.hpp matrix.hpp move.hpp optional.hpp pair.hpp pool.hpp priority_queue.hpp promise.hpp queue.hpp set.hpp shared_ptr.hpp stack.hpp static_cast.hpp string_view.hpp swap.hpp thread_pool.hpp trie.hpp tuple.hpp unique_ptr.hpp unordered_map.hpp variant.hpp vector.hpp

MODULE_NAME := $(notdir $(CURDIR))

all:
	@echo "Template headers"

clean:
	@printf '        [%s] clean: success\n' "$(MODULE_NAME)"

fclean:
	@printf '        [%s] fclean: success\n' "$(MODULE_NAME)"

.PHONY: all clean fclean
