include $(dir $(lastword $(MAKEFILE_LIST)))targets.mk
include $(dir $(lastword $(MAKEFILE_LIST)))sources.mk
include $(dir $(lastword $(MAKEFILE_LIST)))test_groups.mk
include $(dir $(lastword $(MAKEFILE_LIST)))tools.mk
include $(dir $(lastword $(MAKEFILE_LIST)))dependencies.mk
include $(dir $(lastword $(MAKEFILE_LIST)))platform.mk
include $(dir $(lastword $(MAKEFILE_LIST)))flags.mk
include $(dir $(lastword $(MAKEFILE_LIST)))objects.mk
include $(dir $(lastword $(MAKEFILE_LIST)))clean.mk
