BUILD_OBJ_SUFFIX := $(BUILD_OUTPUT_SUFFIX)
ifneq ($(findstring -DLIBFT_TEST_BUILD,$(COMPILE_FLAGS)),)
    BUILD_OBJ_SUFFIX := _test$(BUILD_OUTPUT_SUFFIX)
endif

OBJDIR       := objs$(BUILD_OBJ_SUFFIX)
DEBUG_OBJDIR := objs_debug$(BUILD_OBJ_SUFFIX)
EFFICIENCY_BUILD_OBJ_SUFFIX := $(BUILD_OUTPUT_SUFFIX)
EFFICIENCY_OBJDIR := objs_efficiency$(EFFICIENCY_BUILD_OBJ_SUFFIX)

OBJS       := $(patsubst %.cpp,$(OBJDIR)/%.o,$(SRCS))
DEBUG_OBJS := $(patsubst %.cpp,$(DEBUG_OBJDIR)/%.o,$(SRCS))
EFFICIENCY_OBJS := $(patsubst %.cpp,$(EFFICIENCY_OBJDIR)/%.o,$(EFF_SRCS))
DEPS       := $(OBJS:.o=.d)
DEBUG_DEPS := $(DEBUG_OBJS:.o=.d)
EFFICIENCY_DEPS := $(EFFICIENCY_OBJS:.o=.d)
.SILENT: $(OBJS) $(DEBUG_OBJS) $(EFFICIENCY_OBJS)
