repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
  - repo: local
    hooks:
      - id: make-format
        name: make format
        entry: make
        language: system
        args: ["format"]
        pass_filenames: false
