name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Enforce formatting
        run: |
          make format CLANG_FORMAT=clang-format
          git diff --exit-code

      - name: Build libraries
        run: make all

      - name: Run unit tests
        run: make -C Test libft_tests
